[project]
name = "2048-tutorial"
version = "0.1.0"
description = "Training an LLM to play 2048"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openpipe-art>=0.3.13",
    "python-dotenv>=1.1.1",
    "weave>=0.51.54",
    "ipykernel"
]
